logging:
    level:
        ROOT: DEBUG
        mx.com.dxesoft.lunchtime: DEBUG

spring:
    data:
        mongodb:
            uri: mongodb://aquino:mendez@localhost:32768/xcuaana
    jackson:
            serialization.indent_output: true

server:
    port: 9002


keycloak:
    realm: Xcuaana-dosis
    bearer-only: true
    auth-server-url: http://localhost:8080/auth
    ssl-required: external
    resource: Xcuaana-backend
    verify-token-audience: true
    use-resource-role-mappings: true
    principal-attribute: preferred_username
